### ISSUE TITLE
Advanced Weather Viewer Branch layer sync issue when closing and reopening the AWV.

### ISSUE THREAD

**Issue by patudom** [cosmicds/solar-eclipse-2024#94]
In this screenshot, I was displaying the 8-day, all years median on the map, then I closed the AWV. Now that I've reopened the AWV, the cloud layer is not displaying, but "show on map" is no longer active. I have to click any other choice (say, 1-day), then go back to 8-day to redisplay the 8-day data.
<img width="1185" alt="Screenshot 2024-03-12 at 12 30 26 PM" src="https://github.com/cosmicds/solar-eclipse-2024/assets/12750048/70dcd32c-49a9-4f66-b2d6-e1f6422879e6">

Possible solutions - make the "show on map" button active when we reopen, or keep the cloud layer displayed when we reopen.

**Comment by patudom** [comment]
If we use `v-show` (which hides component) instead of `v-if` (which rebuilds component) that would keep the AWV state consistent, but that might degrade performance for main app. So probably want to pass props to component.

**Comment by johnarban** [comment]
so this is in a dialog. turns out the issue was just that I was turning `displayData` variable, so the component appeared to reset. the state is preserved as a dialog.

**Comment by johnarban** [comment]
Reopening this issue - So the AWV preserves it's state, but what is going wrong is that the `LocationSelector` does not. Vue saves the AWV state (it is in a dialog) but the `LocationSelector` (and any other child components) are removed. What happens is that it seems like `this.map` is `null` when it gets to the `parseResult` function. `setup` is getting run, but seems like `this.map` is not getting set soon enough. This seems to be because `updateCloudCover` uses `this.map` but is called in the `setup` function before `this.map` is set. #93 resolves this by moving `updateCloudCover` to the end of `setup`
